# Generated by Django 3.0.8 on 2020-07-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrandExchange', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='high_alch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='low_alch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quest_item',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='release_date',
            field=models.CharField(default='default', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='wiki_exchange',
            field=models.URLField(default='https://www.google.com', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='wiki_name',
            field=models.CharField(default='https://www.google.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='wiki_url',
            field=models.URLField(default='https://www.google.com', max_length=400),
            preserve_default=False,
        ),
    ]
