# Generated by Django 3.0.8 on 2020-07-19 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GrandExchange', '0003_auto_20200715_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buy_average', models.IntegerField()),
                ('buy_quantity', models.IntegerField()),
                ('overall_average', models.IntegerField()),
                ('sell_average', models.IntegerField()),
                ('sell_quantity', models.IntegerField()),
                ('store_price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrandExchange.Item')),
            ],
        ),
    ]
