# Generated by Django 3.0.8 on 2020-07-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrandExchange', '0004_auto_20200718_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='overall_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
