# Generated by Django 3.0.8 on 2020-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrandExchange', '0005_auto_20200718_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='release_date',
            field=models.DateField(),
        ),
    ]
