# Generated by Django 3.0.8 on 2020-07-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrandExchange', '0006_auto_20200719_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='high_alch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='low_alch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quest_item',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='wiki_exchange',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='wiki_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='wiki_url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
