ALPHABET = [
    "%23",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
]

URLS = {
    "GE": "http://services.runescape.com/m=itemdb_oldschool/api/catalogue/",
    "OSBOX": "https://api.osrsbox.com/",
    "OSBUDDY": "https://rsbuddy.com/exchange/",
    "OSBGOOGLE": "https://storage.googleapis.com/osb-exchange/",
    "CLOUDINARY": "https://res.cloudinary.com/rhartman99/image/fetch/",
}
